from api.config import config
from api.services.chat_room.tools import (
    ASK_LEGITRON_TOOL,
    ASK_MEDITRON_TOOL,
    CREATE_ANALYSIS_TOOL,
    DUMMY_TOOL,
    GET_ANALYSIS_TOOL,
    GET_HUMANITARIAN_CONTEXT_TOOL,
    GET_NATURAL_EVENTS_CONTEXT_TOOL,
    GET_WHO_PUBLICATION_CONTENT_TOOL,
    LIST_ANALYSES_TOOL,
    RECALL_EVENTS_TOOL,
    RECORD_EVENT_TOOL,
    SAVE_WHY_ANSWER_TOOL,
    SAVE_WHY_QUESTION_TOOL,
    SEARCH_WHO_PUBLICATIONS_TOOL,
    SET_ROOT_CAUSE_TOOL,
    HumConnectMCPProxy,
    ToolSet,
)

DEFAULT_LOCAL_TOOLS = (
    DUMMY_TOOL,
    ASK_MEDITRON_TOOL,
    ASK_LEGITRON_TOOL,
    RECORD_EVENT_TOOL,
    RECALL_EVENTS_TOOL,
    GET_NATURAL_EVENTS_CONTEXT_TOOL,
    GET_HUMANITARIAN_CONTEXT_TOOL,
    SEARCH_WHO_PUBLICATIONS_TOOL,
    GET_WHO_PUBLICATION_CONTENT_TOOL,
    CREATE_ANALYSIS_TOOL,
    SAVE_WHY_QUESTION_TOOL,
    SAVE_WHY_ANSWER_TOOL,
    GET_ANALYSIS_TOOL,
    SET_ROOT_CAUSE_TOOL,
    LIST_ANALYSES_TOOL,
)

SANIHUB_MCP_PROXY = HumConnectMCPProxy(
    mcp_name="sanihub",
    server_url=config.SANIHUB_MCP_URL,
    timeout_seconds=config.SANIHUB_MCP_TIMEOUT_SECONDS,
    allowed_tools=frozenset({"knowledgeSearch", "getDocumentContent"}),
)

HUMCONNECT_TOOL_SET = ToolSet(
    DEFAULT_LOCAL_TOOLS,
    tool_providers=(SANIHUB_MCP_PROXY,),
)
