"""added profile editable fields

Revision ID: 128dd236b96b
Revises: 3f7a9d2c1e5b
Create Date: 2026-07-01 17:16:21.702519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '128dd236b96b'
down_revision: Union[str, None] = '3f7a9d2c1e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recordedevent_event_location_trgm'), table_name='recordedevent', postgresql_ops={'(event_location::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_recordedevent_event_name_trgm'), table_name='recordedevent', postgresql_ops={'event_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_recordedevent_original_text_trgm'), table_name='recordedevent', postgresql_ops={'original_text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_recordedevent_tags_gin'), table_name='recordedevent', postgresql_using='gin')
    op.drop_index(op.f('ix_recordedevent_tags_text_trgm'), table_name='recordedevent', postgresql_ops={'(tags::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.add_column('userprofile', sa.Column('profession', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('userprofile', sa.Column('profession_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('userprofile', sa.Column('center_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('userprofile', sa.Column('action_radius_km', sa.Float(), nullable=True))
    op.add_column('userprofile', sa.Column('location_extra', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('userprofile', sa.Column('organisation', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('userprofile', sa.Column('mother_tongue', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint(op.f('userprofile_keycloak_sub_key'), 'userprofile', type_='unique')
    op.drop_index(op.f('ix_userprofile_keycloak_sub'), table_name='userprofile')
    op.create_index(op.f('ix_userprofile_keycloak_sub'), 'userprofile', ['keycloak_sub'], unique=True)
    op.create_index(op.f('ix_userprofile_profession_category'), 'userprofile', ['profession_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userprofile_profession_category'), table_name='userprofile')
    op.drop_index(op.f('ix_userprofile_keycloak_sub'), table_name='userprofile')
    op.create_index(op.f('ix_userprofile_keycloak_sub'), 'userprofile', ['keycloak_sub'], unique=False)
    op.create_unique_constraint(op.f('userprofile_keycloak_sub_key'), 'userprofile', ['keycloak_sub'], postgresql_nulls_not_distinct=False)
    op.drop_column('userprofile', 'mother_tongue')
    op.drop_column('userprofile', 'organisation')
    op.drop_column('userprofile', 'location_extra')
    op.drop_column('userprofile', 'action_radius_km')
    op.drop_column('userprofile', 'center_address')
    op.drop_column('userprofile', 'profession_category')
    op.drop_column('userprofile', 'profession')
    op.create_index(op.f('ix_recordedevent_tags_text_trgm'), 'recordedevent', [sa.literal_column('(tags::text)')], unique=False, postgresql_ops={'(tags::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_recordedevent_tags_gin'), 'recordedevent', [sa.literal_column('(tags::jsonb)')], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_recordedevent_original_text_trgm'), 'recordedevent', ['original_text'], unique=False, postgresql_ops={'original_text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_recordedevent_event_name_trgm'), 'recordedevent', ['event_name'], unique=False, postgresql_ops={'event_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_recordedevent_event_location_trgm'), 'recordedevent', [sa.literal_column('(event_location::text)')], unique=False, postgresql_ops={'(event_location::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###
