"""add_root_cause_analysis_mnemonic_id

Revision ID: d9711ec33544
Revises: 8e1aa18725cb
Create Date: 2026-08-10 17:31:17.714059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd9711ec33544'
down_revision: Union[str, None] = '8e1aa18725cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Add the chat-scoped mnemonic column to the parent table.
    op.add_column('rootcauseanalysis', sa.Column('analysis_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # 2. Backfill existing analyses with sequential per-chat mnemonics.
    op.execute("""
        WITH numbered AS (
            SELECT
                id,
                chat_id,
                ROW_NUMBER() OVER (PARTITION BY chat_id ORDER BY created_at) AS n
            FROM rootcauseanalysis
        )
        UPDATE rootcauseanalysis
        SET analysis_id = 'rca-' || numbered.n
        FROM numbered
        WHERE rootcauseanalysis.id = numbered.id
    """)

    # 3. Enforce non-nullability and uniqueness on the parent table.
    op.alter_column('rootcauseanalysis', 'analysis_id', existing_type=sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    op.create_index(op.f('ix_rootcauseanalysis_analysis_id'), 'rootcauseanalysis', ['analysis_id'], unique=False)
    op.create_unique_constraint('uq_rootcauseanalysis_chat_analysis_id', 'rootcauseanalysis', ['chat_id', 'analysis_id'])

    # 4. Add chat_id to the step table (nullable until backfilled).
    op.add_column('rootcauseanalysisstep', sa.Column('chat_id', sa.Uuid(), nullable=True))

    # 5. Backfill chat_id from the parent analysis.
    op.execute("""
        UPDATE rootcauseanalysisstep
        SET chat_id = rootcauseanalysis.chat_id
        FROM rootcauseanalysis
        WHERE rootcauseanalysisstep.analysis_id::text = rootcauseanalysis.id::text
    """)

    # 6. Add a temporary column for the mnemonic and backfill it from the parent.
    op.add_column('rootcauseanalysisstep', sa.Column('mnemonic', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("""
        UPDATE rootcauseanalysisstep
        SET mnemonic = rootcauseanalysis.analysis_id
        FROM rootcauseanalysis
        WHERE rootcauseanalysisstep.analysis_id::text = rootcauseanalysis.id::text
    """)

    # 7. Drop the old foreign key and the old UUID analysis_id column, then rename the mnemonic column.
    op.drop_constraint('rootcauseanalysisstep_analysis_id_fkey', 'rootcauseanalysisstep', type_='foreignkey')
    op.drop_column('rootcauseanalysisstep', 'analysis_id')
    op.alter_column('rootcauseanalysisstep', 'mnemonic', new_column_name='analysis_id', existing_type=sqlmodel.sql.sqltypes.AutoString(), nullable=True)

    # 8. Enforce non-nullability on the step table.
    op.alter_column('rootcauseanalysisstep', 'chat_id', existing_type=sa.Uuid(), nullable=False)
    op.alter_column('rootcauseanalysisstep', 'analysis_id', existing_type=sqlmodel.sql.sqltypes.AutoString(), nullable=False)

    # 9. Add indexes and the composite foreign key.
    op.create_index(op.f('ix_rootcauseanalysisstep_chat_id'), 'rootcauseanalysisstep', ['chat_id'], unique=False)
    op.create_index(op.f('ix_rootcauseanalysisstep_analysis_id'), 'rootcauseanalysisstep', ['analysis_id'], unique=False)
    op.create_foreign_key('fk_rootcauseanalysisstep_analysis', 'rootcauseanalysisstep', 'rootcauseanalysis', ['chat_id', 'analysis_id'], ['chat_id', 'analysis_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Drop the composite foreign key.
    op.drop_constraint('fk_rootcauseanalysisstep_analysis', 'rootcauseanalysisstep', type_='foreignkey')

    # 2. Recreate the old UUID analysis_id from the parent table.
    op.add_column('rootcauseanalysisstep', sa.Column('old_analysis_id', sa.Uuid(), nullable=True))
    op.execute("""
        UPDATE rootcauseanalysisstep
        SET old_analysis_id = rootcauseanalysis.id
        FROM rootcauseanalysis
        WHERE rootcauseanalysisstep.chat_id = rootcauseanalysis.chat_id
          AND rootcauseanalysisstep.analysis_id = rootcauseanalysis.analysis_id
    """)
    op.drop_index(op.f('ix_rootcauseanalysisstep_analysis_id'), table_name='rootcauseanalysisstep')
    op.drop_index(op.f('ix_rootcauseanalysisstep_chat_id'), table_name='rootcauseanalysisstep')
    op.drop_column('rootcauseanalysisstep', 'analysis_id')
    op.drop_column('rootcauseanalysisstep', 'chat_id')
    op.alter_column('rootcauseanalysisstep', 'old_analysis_id', new_column_name='analysis_id', existing_type=sa.Uuid(), nullable=True)
    op.alter_column('rootcauseanalysisstep', 'analysis_id', existing_type=sa.Uuid(), nullable=False)
    op.create_index(op.f('ix_rootcauseanalysisstep_analysis_id'), 'rootcauseanalysisstep', ['analysis_id'], unique=False)
    op.create_foreign_key('rootcauseanalysisstep_analysis_id_fkey', 'rootcauseanalysisstep', 'rootcauseanalysis', ['analysis_id'], ['id'])

    # 3. Remove the mnemonic from the parent table.
    op.drop_constraint('uq_rootcauseanalysis_chat_analysis_id', 'rootcauseanalysis', type_='unique')
    op.drop_index(op.f('ix_rootcauseanalysis_analysis_id'), table_name='rootcauseanalysis')
    op.drop_column('rootcauseanalysis', 'analysis_id')
    # ### end Alembic commands ###
