"""added lat lon for locations

Revision ID: 37a26f3a92e1
Revises: 59a11d8b80b6
Create Date: 2026-07-02 00:03:21.051197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a26f3a92e1'
down_revision: Union[str, None] = '59a11d8b80b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('center_latitude', sa.Float(), nullable=True))
    op.add_column('userprofile', sa.Column('center_longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userprofile', 'center_longitude')
    op.drop_column('userprofile', 'center_latitude')
    # ### end Alembic commands ###
