"""add root cause analysis tables

Revision ID: 879882220532
Revises: cd394fd503ad
Create Date: 2026-07-21 17:12:43.711787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '879882220532'
down_revision: Union[str, None] = 'cd394fd503ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rootcauseanalysis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.Uuid(), nullable=False),
    sa.Column('initiated_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('source_message_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chatsession.id'], ),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['userprofile.id'], ),
    sa.ForeignKeyConstraint(['source_message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rootcauseanalysis_chat_id'), 'rootcauseanalysis', ['chat_id'], unique=False)
    op.create_index(op.f('ix_rootcauseanalysis_created_at'), 'rootcauseanalysis', ['created_at'], unique=False)
    op.create_index(op.f('ix_rootcauseanalysis_initiated_by_user_id'), 'rootcauseanalysis', ['initiated_by_user_id'], unique=False)
    op.create_index(op.f('ix_rootcauseanalysis_source_message_id'), 'rootcauseanalysis', ['source_message_id'], unique=False)
    op.create_index(op.f('ix_rootcauseanalysis_status'), 'rootcauseanalysis', ['status'], unique=False)
    op.create_table('rootcauseanalysisstep',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('step_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['rootcauseanalysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rootcauseanalysisstep_analysis_id'), 'rootcauseanalysisstep', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_rootcauseanalysisstep_created_at'), 'rootcauseanalysisstep', ['created_at'], unique=False)
    op.create_index(op.f('ix_rootcauseanalysisstep_level'), 'rootcauseanalysisstep', ['level'], unique=False)
    op.create_index(op.f('ix_rootcauseanalysisstep_position'), 'rootcauseanalysisstep', ['position'], unique=False)
    op.create_index(op.f('ix_rootcauseanalysisstep_step_type'), 'rootcauseanalysisstep', ['step_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rootcauseanalysisstep_step_type'), table_name='rootcauseanalysisstep')
    op.drop_index(op.f('ix_rootcauseanalysisstep_position'), table_name='rootcauseanalysisstep')
    op.drop_index(op.f('ix_rootcauseanalysisstep_level'), table_name='rootcauseanalysisstep')
    op.drop_index(op.f('ix_rootcauseanalysisstep_created_at'), table_name='rootcauseanalysisstep')
    op.drop_index(op.f('ix_rootcauseanalysisstep_analysis_id'), table_name='rootcauseanalysisstep')
    op.drop_table('rootcauseanalysisstep')
    op.drop_index(op.f('ix_rootcauseanalysis_status'), table_name='rootcauseanalysis')
    op.drop_index(op.f('ix_rootcauseanalysis_source_message_id'), table_name='rootcauseanalysis')
    op.drop_index(op.f('ix_rootcauseanalysis_initiated_by_user_id'), table_name='rootcauseanalysis')
    op.drop_index(op.f('ix_rootcauseanalysis_created_at'), table_name='rootcauseanalysis')
    op.drop_index(op.f('ix_rootcauseanalysis_chat_id'), table_name='rootcauseanalysis')
    op.drop_table('rootcauseanalysis')
    # ### end Alembic commands ###
