"""add_recorded_event_end_dates

Revision ID: ea62939d14ff
Revises: 01529dc7b576
Create Date: 2026-07-21 13:37:25.848954

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea62939d14ff"
down_revision: Union[str, None] = "01529dc7b576"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recordedevent",
        sa.Column("event_end_datetime", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "recordedevent",
        sa.Column(
            "event_end_date_granularity",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    op.add_column(
        "recordedevent",
        sa.Column(
            "event_end_date_precision",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    op.add_column(
        "recordedevent",
        sa.Column("event_end_date_input", sa.JSON(), nullable=True),
    )
    op.create_check_constraint(
        "ck_recordedevent_event_date_range",
        "recordedevent",
        "event_end_datetime IS NULL OR event_datetime IS NULL "
        "OR event_end_datetime >= event_datetime",
    )
    op.create_index(
        op.f("ix_recordedevent_event_end_date_granularity"),
        "recordedevent",
        ["event_end_date_granularity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recordedevent_event_end_date_precision"),
        "recordedevent",
        ["event_end_date_precision"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recordedevent_event_end_datetime"),
        "recordedevent",
        ["event_end_datetime"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_recordedevent_event_end_datetime"), table_name="recordedevent"
    )
    op.drop_index(
        op.f("ix_recordedevent_event_end_date_precision"),
        table_name="recordedevent",
    )
    op.drop_index(
        op.f("ix_recordedevent_event_end_date_granularity"),
        table_name="recordedevent",
    )
    op.drop_constraint(
        "ck_recordedevent_event_date_range",
        "recordedevent",
        type_="check",
    )
    op.drop_column("recordedevent", "event_end_date_input")
    op.drop_column("recordedevent", "event_end_date_precision")
    op.drop_column("recordedevent", "event_end_date_granularity")
    op.drop_column("recordedevent", "event_end_datetime")
    # ### end Alembic commands ###
